
version: 1.0.0.{build}

clone_folder: c:\projects\kky-ui

branches:
  only:
    - master

os:
  - Visual Studio 2015
platform:
  - x64
  - x86
  - ARM
configuration:
  - Release

matrix:
  fast_finish: true

before_build:
  - cd c:\projects\kky-ui
  - mkdir build
  - cd build
  - cmake ..
  
build_script:
  - cmake --build .


